name: On Push Import conversation

on: push

env:
  WORKDIR: workdir
  SALESFORCE_ENDPOINT: https://power-efficiency-5851-dev-ed.my.salesforce.com/services/apexrest/delpha/ImportConv/

jobs:
  upload_conversations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Get changed zip files
        id: changed-zip-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            conversations/*.zip

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install requests package
        run: pip install requests

      - name: Upload all changed zips
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          SALESFORCE_ENDPOINT: ${{ secrets.SALESFORCE_ENDPOINT }}
        run: |
          for file in ${{ steps.changed-zip-files.outputs.all_changed_files }}; do
            python $file ${{ steps.commit.outputs.short }}
          done
